backend:
  name: git-gateway

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "articles"
    label: "Article"
    folder: "content"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Abstract", name: "abstract", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
